dist: xenial
language: generic
git:
  depth: false
install:
- python -m pip install --user pygments restructuredtext-lint
script:
- shellcheck git*
- prove -v
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
