dist: trusty
sudo: false
language: generic
install:
- python -m pip install --user pygments restructuredtext-lint
script:
- shellcheck git*
- ./git-clone-to-bundle https://github.com/jwilk/git-toolbox
- file git-toolbox.gb
- ./git-forall status
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
