dist: trusty
sudo: false
language: generic
addons:
  apt:
    packages:
    - python-docutils
    - python-pygments
    - shellcheck
script:
- shellcheck git*
- ./git-clone-to-bundle https://github.com/jwilk/git-toolbox
- file git-toolbox.gb
- private/check-rst

# vim:ts=2 sts=2 sw=2 et
