#!/bin/sh

# Copyright © 2016-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -u
findopts=
filter='cat'
while getopts 'LF:' opt
do
    case "$opt" in
        L) findopts='-L';;
        F) filter="$OPTARG";;
        *) exit 1;;
    esac
done
shift $((OPTIND - 1))
template=$(git -C / config --get forall.template) || template='==> %s <=='
find $findopts . -xdev -type d \( -name '.git' \) -print -prune \
| $filter \
| while read -r dir
do
    dir="${dir%/.git}"
    dir="${dir#./}"
    # shellcheck disable=SC2059
    printf "$template"'\n' "$dir"
    git -C "$dir" "$@" < /dev/null
    printf '\n'
done

# vim:ts=4 sts=4 sw=4 et
