#!/usr/bin/env bash

# Copyright © 2024 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
set -o pipefail

git ls-files --deleted -z \
| git update-index --assume-unchanged -z --stdin

# vim:ts=4 sts=4 sw=4 et
