#!/bin/sh
find -xdev -type d \( -name '.git' -o -path '*/.hg/git' \) -print -prune \
| while read -r dir
do
    dir="${dir%/.git}"
    dir="${dir#./}"
    printf '[\033[1m%s\033[0m]\n' "$dir"
    git -C "$dir" "$@"
    printf '\n'
done

# vim:ts=4 sts=4 sw=4 et
