#!/bin/sh

# Copyright © 2024-2025 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

##>> convert tags/* branches (as created by git-svn)
##>> into proper tags

set -e -u
git push . 'refs/remotes/origin/tags/*:refs/tags/*'
template='git branch -rd %(refname:strip=2)'
script=$(git for-each-ref 'refs/remotes/origin/tags/' --shell --format "$template")
eval "$script"

# vim:ts=4 sts=4 sw=4 et
