#!/bin/sh

# Copyright © 2017-2019 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

usage()
{
    printf 'Usage:\n  %s TARFILE [TARFILE...]\n  %s -o DIR TARFILE\n' "$prog" "$prog"
}

set -e -u -C
prog="${0##*/}"
xdest=
while getopts 'ho:' opt
do
    case "$opt" in
        h) usage; exit 0;;
        o) xdest="$OPTARG";;
        *) exit 1;;
    esac
done
shift $((OPTIND - 1))
if [ $# -eq 0 ]
then
    usage >&2
    exit 1
fi
if [ -n "$xdest" ] && [ "${xdest#/}" = "$xdest" ]
then
    xdest="$PWD/$xdest"
fi
config_regexps=$(tr '\n' '|' <<'EOF'
\[core\]
\trepositoryformatversion = 0
\tfilemode = true
\tbare = false
\tlogallrefupdates = true
\[remote "origin"\]
\turl = (https?|git|file)://([][:/?#@!$&()*+,;a-zA-Z0-9._/~-]|%[0-9a-fA-F]{2})+
\tfetch = [+]refs/heads/[*]:refs/remotes/origin/[*]
\[branch "[a-zA-Z0-9._-]+"\]
\tremote = origin
\tmerge = refs/heads/\S+
EOF
)
for tarfile in "$@"
do
    name="$tarfile"
    name="${name%/}"
    for ext in tar tar.gz tar.bz2 tar.xz tar.zst
    do
        sname="${name%.$ext}"
        if [ "$sname" != "$name" ]
        then
            name="$sname"
            break
        fi
    done
    name="${name%.git}"
    name="${name##*/}"
    if [ -n "$xdest" ]
    then
        dest="$xdest"
    else
        dest="$PWD/${name}"
    fi
    mkdir "$dest"
    mkdir "$dest/.git.tmp"
    tar -xf "$tarfile" --strip=1 -C "$dest/.git.tmp" --wildcards \
        '*/HEAD' \
        '*/branches/' \
        '*/logs/' \
        '*/objects/' \
        '*/packed-refs' \
        '*/refs/' \
        '*/config'
    if grep -q -v -x -P "$config_regexps" "$dest/.git.tmp/config"
    then
        printf '%s: suspicious configuration lines found:\n' "$dest/.git.tmp/config" >&2
        # shellcheck disable=SC2063
        grep -v -x -P "$config_regexps" "$dest/.git.tmp/config" | grep --color=auto '.*' >&2
        exit 1
    fi
    mv "$dest/.git.tmp" "$dest/.git"
    printf '%s:\n' "$dest"
    git -C "$dest/" reset --hard
done


# vim:ts=4 sts=4 sw=4 et
