#!/usr/bin/env bash

# Copyright © 2024 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
set -o pipefail

git config core.commitGraph true
git show-ref -s \
| git commit-graph write --stdin-commits

# vim:ts=4 sts=4 sw=4 et
