#!/bin/sh

# Copyright © 2024 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

##>> convert tags/* branches (as created by git-svn)
##>> into proper tags

set -e -u
template='git tag %(refname:lstrip=4) %(objectname) && git branch -rd %(refname:strip=2)'
v=$(git for-each-ref 'refs/remotes/origin/tags/' --shell --format "$template")
eval "$v"

# vim:ts=4 sts=4 sw=4 et
