#!/bin/sh

# Copyright © 2016-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
changelog=$(git ls-files doc/changelog doc/NEWS | LC_ALL=C sort | tail -n1)
if [ -z "$changelog" ]
then
    printf '%s: no changelog found\n' "${0##*/}" >&2
    exit 1
fi
read -r project version release <<EOF
$(git cat-file blob "HEAD:$changelog" | head -n1)
EOF
version="${version%)}"
version="${version#(}"
release="${release%;}"
exec git tag "$version" -asm "$project $version"

# vim:ts=4 sts=4 sw=4 et
