#!/bin/sh

# Copyright © 2024 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
prog="${0##*/}"
if [ $# -ne 1 ]
then
    printf 'Usage: %s BRANCH\n' "$prog" >&2
    exit 1
fi
branch="$1"
git merge "$branch"
git branch -d "$branch"

# vim:ts=4 sts=4 sw=4 et
