#!/bin/sh

# Copyright © 2022-2024 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
prog="${0##*/}"
if [ $# -eq 2 ]
then
    host="$1"
    url="$2"
else
    printf 'Usage: %s HOST URL\n' "$prog" >&2
    exit 1
fi
set -x
tmpdir=$(ssh "$host" -- mktemp -dt git-tmpfetch.XXXXXX)
# shellcheck disable=SC2029
ssh "$host" -- git clone --mirror "$url" "$tmpdir"
git -c "url.ssh://$host$tmpdir.insteadOf=$url" clone "$url"
# shellcheck disable=SC2029
ssh "$host" -- rm -rf "$tmpdir"

# vim:ts=4 sts=4 sw=4 et
