#!/bin/sh

# Copyright © 2016-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

usage()
{
    printf 'Usage:\n  %s [-p PROJECT] TAG [TAG...]\n  %s [-p PROJECT] -a\n' "$prog" "$prog"
}

set -e -u
prog="${0##*/}"
project=${PWD##*/}
opt_all=
while getopts 'hp:a' opt
do
    case "$opt" in
        h) usage; exit 0;;
        p) project="$OPTARG";;
        a) opt_all=1;;
        *) exit 1;;
    esac
done
shift $((OPTIND - 1))
if [ $# -eq 0 ]
then
    if [ "$opt_all" ]
    then
        s=$(git for-each-ref --shell --format='set -- "$@" %(refname:lstrip=2)' refs/tags/);
        eval "set -e; $s"
    else
        usage >&2
        exit 1
    fi
elif [ "$opt_all" ]
then
    usage >&2
    exit 1
fi
retag()
{
    g="$(git log -1 --format=%ci "$1")"
    export GIT_COMMITTER_DATE="$g"
    git tag -m "$project $1" -f -s -a "$1" "$1^{}";
}
for t
do
    retag "$t"
done

# vim:ts=4 sts=4 sw=4 et
