#!/bin/sh

# Copyright © 2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
url="$1"
name=$(basename "${url%.git}")
git clone --bare "$url" "$name"
git -C "$name" bundle create "../${name}.gb" --all
rm -rf "$name"
