#!/bin/sh

# Copyright © 2017-2019 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

usage()
{
    printf 'Usage:\n  %s URL [URL...]\n  %s -o FILE URL\n' "$prog" "$prog"
}

set -e -u -C
prog="${0##*/}"
xdest=
while getopts 'ho:' opt
do
    case "$opt" in
        h) usage; exit 0;;
        o) xdest="$OPTARG";;
        *) exit 1;;
    esac
done
shift $((OPTIND - 1))
if [ $# -eq 0 ]
then
    usage >&2
    exit 1
fi
if [ -n "$xdest" ] && [ "${xdest#/}" = "$xdest" ]
then
    xdest="$PWD/$xdest"
fi
for url in "$@"
do
    if [ -n "$xdest" ]
    then
        dest="$xdest"
    else
        name="$url"
        name="${name%/}"
        name="${name%.git}"
        name="${name##*/}"
        dest="$PWD/${name}.gb"
    fi
    true > "$dest"
    tmpdir=$(mktemp -d -t git-clone-to-bundle.XXXXXX)
    git clone --mirror "$url" "$tmpdir/repo"
    git -C "$tmpdir/repo" bundle create "$dest" --all
    rm -rf "$tmpdir"
done

# vim:ts=4 sts=4 sw=4 et
