#!/usr/bin/env bash

# Copyright © 2024 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
set -o pipefail

prefix=$(head -c 12 /dev/urandom | base64 | tr +/ -_)
git diff -U0 --src-prefix="$prefix/" --dst-prefix="$prefix/" "$@" \
| grep -P "^[+](?![+][+] $prefix/)"

# vim:ts=4 sts=4 sw=4 et
