#!/usr/bin/env bash

# Copyright © 2024 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

if [ $# -ne 1 ]
then
    prog=${0#*/}
    printf 'Usage: %s PATH\n' "$prog" >&2
    exit 1
fi
path="$1"
hash=$(printf '\21%.0s' $(seq 20))
tree=$(printf "160000 %s\0%s" "$path" "$hash" | git hash-object -t tree -w --stdin)
commit=$(git commit-tree "$tree" <<< 'Add empty directory')
exec git cherry-pick --edit "$commit"

# vim:ts=4 sts=4 sw=4 et
