#!/bin/sh

# Copyright © 2024 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

##>> convert tags/* branches (as created by git-svn)
##>> into proper tags

set -e -u
git push . 'refs/remotes/origin/tags/*:refs/tags/*'
git update-ref -d 'refs/remotes/origin/tags/*'

# vim:ts=4 sts=4 sw=4 et
