#!/bin/sh

# Copyright © 2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

boring1="\
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean"
boring2="\
On branch null
nothing to commit, working tree clean"
out="$(git status "$@")"
rc=$?
case $out in
    "$boring1"|"$boring2")
        ;;
    *)
        printf '%s\n' "$out"
esac
exit $rc

# vim:ts=4 sts=4 sw=4 et
