#!/bin/sh

# Copyright © 2018-2024 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

##>> like "git status",
##>> but ignores boring stuff

boring1="\
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean"
boring2="\
On branch null
nothing to commit, working tree clean"
boring3="\
On branch null

No commits yet

nothing to commit (create/copy files and use \"git add\" to track)"
out="$(git status "$@")"
rc=$?
case $out in
    "$boring1"|"$boring2"|"$boring3")
        ;;
    *)
        printf '%s\n' "$out"
esac
exit $rc

# vim:ts=4 sts=4 sw=4 et
