#!/bin/sh

# Copyright © 2017-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u -C
url="$1"
name=$(basename "${url%.git}")
tmpdir=$(mktemp -d -t git-clone-to-bundle.XXXXXX)
git clone --bare "$url" "$tmpdir/repo"
dest="$PWD/${name}.gb"
true > "$dest"
git -C "$tmpdir/repo" bundle create "$dest" --all
rm -rf "$tmpdir"
