#!/bin/sh

# Copyright © 2016-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

usage()
{
    printf 'Usage: %s [-p PROJECT]\n' "$prog"
}

prog="${0##*/}"
project=
while getopts 'hp:' opt
do
    case "$opt" in
        h) usage; exit 0;;
        p) project="$OPTARG";;
        *) exit 1;;
    esac
done
shift $((OPTIND - 1))
[ -n "$project" ] || project=$(basename "$PWD")
retag()
{
    export GIT_COMMITTER_DATE="$(git log -1 --format=%ci "$1")"
    git tag -m "$project $1" -f -s -a "$1" "$1^{}";
}
for t in $(git tag)
do
    retag $t
done

# vim:ts=4 sts=4 sw=4 et
