#!/usr/bin/env bash

# Copyright © 2024 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

if [ $# -ne 1 ]
then
    prog=${0#*/}
    printf 'Usage: %s PATH\n' "$prog" >&2
    exit 1
fi
path="$1"
hash=$(printf '1%.0s' $(seq 40))
git update-index --add --cacheinfo "160000,$hash,$path"
git restore "$path"

# vim:ts=4 sts=4 sw=4 et
