#!/bin/sh

# Copyright © 2017-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u -C
url="$1"
name="$url"
name="${name%/}"
name="${name%.git}"
name="${name##*/}"
dest="$PWD/${name}.gb"
true > "$dest"
tmpdir=$(mktemp -d -t git-clone-to-bundle.XXXXXX)
git clone --bare "$url" "$tmpdir/repo"
git -C "$tmpdir/repo" bundle create "$dest" --all
rm -rf "$tmpdir"
