name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-22.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: run tests
      run: |
        prove -v
    - name: run shellcheck
      run: |
        shellcheck $(grep -rl '^#!.*sh$' *)
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
